update repo url references
electricitymaps/electricitymaps-contrib pull request #4551
Opened 2022-09-08 17:09 UTC by tonypls

## Issue

## Description

We have added the "s" to the repos, updating all the links I could find that refer to the old repo urls

2022-09-08 17:14 UTC, VIKTORVAV99 requested changes
Looks like CircleCI don't like the capitalization (it works fine in the github links).

Besides that it looks good to me.

2022-09-08 17:14 UTC, VIKTORVAV99 commented on README.md
> +[![Slack Status](https://slack.electricitymaps.com/badge.svg)](https://slack.electricitymaps.com) [![CircleCI](https://circleci.com/gh/electricityMaps/electricitymaps-contrib.svg?style=shield)](https
```suggestion
[![Slack Status](https://slack.electricitymaps.com/badge.svg)](https://slack.electricitymaps.com) [![CircleCI](https://circleci.com/gh/electricityMaps/electricitymaps-contrib.svg?style=shield)](https://circleci.com/gh/electricitymaps/electricitymaps-contrib) [![Twitter Follow](https://img.shields.io/twitter/follow/ElectricityMaps.svg?style=social&label=Follow)](https://twitter.com/ElectricityMaps)
```

2022-09-08 17:24 UTC, tonypls commented on README.md
> +[![Slack Status](https://slack.electricitymaps.com/badge.svg)](https://slack.electricitymaps.com) [![CircleCI](https://circleci.com/gh/electricityMaps/electricitymaps-contrib.svg?style=shield)](https
nice catch :)

2022-09-08 17:25 UTC, VIKTORVAV99 approved these changes

2022-09-08 18:10 UTC, VIKTORVAV99 commented
That cypress test that is failing is one of the flaky ones with a `.click()` method.

But why are we adding the readme to prettierignore?
(it's not really important either way but we might as well just ignore all `.md` files if we want to ignore the "text" files.)

2022-09-09 07:11 UTC, tonypls commented
Ignored the readme because it is custom formatted based on how we want it to look. If you let prettier format it then it escapes any "*", formats JSON and removes padding we have to make it more readable.

2022-09-09 07:26 UTC, VIKTORVAV99 commented
> Ignored the readme because it is custom formatted based on how we want it to look. If you let prettier format it then it escapes any "*", formats JSON and removes padding we have to make it more readable. 

Hmm I thought prettier only removed excess characters (characters with no style impact) and formatted code blocks in markdown but I could be wrong.

I'll look into it though.

2022-09-09 08:46 UTC, tonypls commented
Ah okay, must've been ESLint on my local machine doing the weird formatting.

2022-09-09 08:50 UTC, merged