Update TR Geothermal Values
electricitymaps/electricitymaps-contrib pull request #5074
Opened 2023-02-11 00:30 UTC by SSD1805

Added Geothermal CO2 energy output as per issue 5019

## Issue
https://github.com/electricitymaps/electricitymaps-contrib/issues/5019#issue-1569478266
## Description
 Verify that the values in the paper are valid.
 Create a PR to update the regional emissions if the above task is done.

### Preview

<img width="960" alt="image" src="https://user-images.githubusercontent.com/44541455/218226320-8f5f48fe-719b-4959-840c-7e2888838816.png">

2023-02-11 10:02 UTC, VIKTORVAV99 requested changes
First, I'm not sure it's as easy as this PR makes it out to be. The paper in question uses different values per year so we should as well, preferably going back as far as 2015 till today (or 2024 as the paper suggest)

Secondly, we need to verify these values to make sure they can be trusted.

Thirdly, this PR does not follow the structure that is required for the zone files, which will need to be corrected before this can be merged.

2023-02-11 10:02 UTC, VIKTORVAV99 commented on config/zones/TR.yaml
> +      Turkish geothermal power plants." (2020)
This should follow MLA citation style as and should not contain a line break (`\n`). If needed, you can wrap the whole string in single quotes (`''`).

2023-02-11 10:02 UTC, VIKTORVAV99 commented on config/zones/TR.yaml
> +      datetime: '2020-01-01'
The datetime listed in the paper for the value you added is August 2019, not January 2020.

2023-02-13 09:25 UTC, mathilde-daugy commented on config/zones/TR.yaml
> +      url: https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2020/Akin.pdf
url is not a valid key for this config, we only use source to link to the research paper

2023-02-16 10:39 UTC, mathilde-daugy commented on config/zones/TR.yaml
> +      url: https://pangea.stanford.edu/ERE/db/GeoConf/papers/SGW/2020/Akin.pdf
In [KR.yaml](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/config/zones/KR.yaml), there is a url linked for unknown using the key `_url`

2023-02-20 07:26 UTC, VIKTORVAV99 requested changes
There are still highly questionable changes in here and this will fail in our backend.

Please do take a look how the previous regional sources are formatted.

We also need to make sure we get a accurate value for each year the paper cover before this can be merged, right now we only have data for the end of 2019. We also need to verify these numbers as we can't just take it at face value.

2023-02-20 07:26 UTC, VIKTORVAV99 commented on config/zones/TR.yaml
> +      Value for geothermal: The average emission of these GPPs is 595.92 CO2/kWh respectively, which is significantly lower than 2015 average (887 g/kWh).
Why is this listed under unknown?

2023-03-05 11:26 UTC, VIKTORVAV99 commented
@SSD1805 have you made any progress on this incorporating the feedback here? We can't merge this as is.

2023-04-26 21:28 UTC, VIKTORVAV99 commented
Closing this PR as there has been no response from the author.

2023-04-26 21:28 UTC, closed without merging