use-resze-observer impl.
electricitymaps/electricitymaps-contrib pull request #5166
Opened 2023-03-06 18:26 UTC by 15Arindam

## Issue

Charts don't re-size when the window size changes #5141

## Description

Implemented [use-resize-observer](https://github.com/ZeeCoder/use-resize-observer) hook for this scenario

### Preview

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-03-07 15:28 UTC, VIKTORVAV99 reviewed
I have been testing this locally and while the resizing seem to work now it seems to have broken this code somehow:
https://github.com/electricitymaps/electricitymaps-contrib/blob/d7250e9af451eda922ad4c7aaadb058aff469840/web/src/features/charts/graphUtils.ts#L20-L22

I'm not really sure why it broke and have not had the time to dig into it further but until that is fixed we can't merge this as it breaks hovering over the (some) of the graphs.

2023-03-09 17:38 UTC, VIKTORVAV99 commented
@15Arindam please do not use force push, it makes it impossible to review changes since the last commit.

2023-03-09 17:50 UTC, VIKTORVAV99 reviewed
As far as I can tell everything is working as expected now, nice work!

In order for this to pass the CI though you need to run `pnpx prettier --write .` in the `/web` folder.

2023-03-13 22:28 UTC, VIKTORVAV99 requested changes
There seems to be some inconsistencies with the initial values that need to be corrected and/or explained, this PR is currently not consistent all the way and these seems to be no real need to set an initial value in the first place.

2023-03-13 22:28 UTC, VIKTORVAV99 commented on web/src/features/charts/bar-breakdown/BarBreakdownChart.tsx
> +  const { ref, width: observerWidth = 0 } = useResizeObserver();
Why do we need an initial value here?

2023-03-13 22:28 UTC, VIKTORVAV99 commented on web/src/features/charts/elements/AreaGraph.tsx
> +  const { width: observerWidth = 0, height: observerHeight = 0 } =
and here?

These will become negative initially and well negative width and height don't really work.

2023-03-13 22:28 UTC, VIKTORVAV99 commented on web/src/features/exchanges/ExchangeLayer.tsx
> +  const { ref, height = 0, width = 0 } = useResizeObserver();
Here we also set them to 0 initially. Why?

2023-03-13 22:28 UTC, VIKTORVAV99 commented on web/src/features/time/TimeAxis.tsx
> +  const width = observerWidth - 24;
This will also be negative initially.

2023-03-13 22:28 UTC, VIKTORVAV99 commented on web/src/features/weather-layers/solar/SolarLayer.tsx
> +  const { width, height } = useResizeObserver({ ref: reference });
Here we don't set an initial value, this seems correct for the usecase.

2023-03-13 22:28 UTC, VIKTORVAV99 commented on web/src/features/weather-layers/wind-layer/WindLayer.tsx
> +  const { height = 0, width = 0 } = useResizeObserver<HTMLCanvasElement>({ ref: reference });
and here we set it once again? Why the inconsistency and why is the initial values needed?

2023-03-13 22:29 UTC, VIKTORVAV99 commented
@15Arindam I noticed you created a new PR but I would prefer we keep using this one to preserve he discussions and comments in the original PR.

2023-03-15 04:33 UTC, 15Arindam commented
Hi @VIKTORVAV99 , The type value of width, height returned from `useResizeObserver` hook is `undefined | number` , methods doesnt' throw typescript error , there I kept as is otherplace I defaulted with zero. But as you pointed out I missed the negative value cases.

2023-03-15 09:14 UTC, VIKTORVAV99 submitted a review, later dismissed
LGTM! 🎉

Thanks for implementing the change!
I'll merge this later today after #5183 is merged to see that the tests are still passing but they should be as I saw no changes that should have affected them.

2023-03-16 18:36 UTC, VIKTORVAV99 commented
@tonypls do you know why cypress is failing in here? As far as I can tell there is no direct changes that should affect the tests.

2023-03-16 19:48 UTC, tonypls commented
> @tonypls do you know why cypress is failing in here? As far as I can tell there is no direct changes that should affect the tests.

It looks like the resize observer doesn't see the size of the container of the AreaGraph in cypress. The graph just keeps growing so Cypress in unable to hover

2023-03-20 15:56 UTC, VIKTORVAV99 commented on web/cypress/e2e/countrypanel.spec.ts
@tonypls would you mind reviwing the changes to the tests here?
I'm not super familiar with how cypress works 🙂

2023-03-20 20:33 UTC, tonypls commented on web/cypress/e2e/countrypanel.spec.ts
Damn, looks like there's some sort of loop in the width observer.

https://user-images.githubusercontent.com/18622768/226459378-c5337922-130e-4168-b17c-e85a2937b434.mov

2025-03-10 22:44 UTC, madsnedergaard commented
Closing this for now, it was a nice contribution but we need Cypress tests to still work - if anyone wants to pick this up again feel free to do so :)

2025-03-10 22:44 UTC, closed without merging