#5426 new CZ (CEPS) parser is missing pumping demand for pumped hydro
electricitymaps/electricitymaps-contrib pull request #5473
Opened 2023-06-16 15:37 UTC by Frantisek12

## Issue

[](https://github.com/electricitymaps/electricitymaps-contrib/issues/5426)

Fixes: #5426 

## Description

fetch_consumption added and used to obtain pumping demand. fetch_consumption() not replaced in configuration for entsoe. Could be done if the format is correct. Please check

### Preview

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-06-30 07:49 UTC, Frantisek12 commented on parsers/CZ.py
> +                        "pumping"
this weird formatting was done by `poetry run format`

2024-02-07 13:10 UTC, VIKTORVAV99 requested changes
Sorry for taking so long with this, that's on me, but there are a lot of type errors and undocumented logic at work here. I don't think we can merge it as is.

2024-02-07 13:10 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +        for values in data_tag:
This whole looping over xml elements is filled with type errors. Not sure we can merge it as is.

2024-02-07 13:10 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +                date_time = values["date"]
Causing several issues here.

2024-02-07 13:10 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +def fetch_consumption(
This should not be named fetch_consumption if it don't return the expected consumption element.

Should be renamed to get_consumption

2025-03-10 23:00 UTC, madsnedergaard commented
Closing due to inactivity, feel free to reopen if you decide to pick this up again :)

2025-03-10 23:00 UTC, closed without merging