Added emission factors for Ontario
electricitymaps/electricitymaps-contrib pull request #5524
Opened 2023-06-28 01:20 UTC by Nil-Cipher

## Issue
Closes #4886

## Description

Added emission numbers for various electricity generation types for Ontario.

### Double check

- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-06-28 01:20 UTC, Nil-Cipher commented
@VIKTORVAV99 made PR for review!

2023-06-28 10:00 UTC, VIKTORVAV99 requested changes
Thanks for opening the PR!

Please note the formatting in the source object at the bottom and the source formatting in the specific values should match.

There should also not be any new lines in the sources.
(This feedback was also provided on the other open PR.)

2023-06-28 17:23 UTC, Nil-Cipher commented
Copied the original source text.

2023-07-08 14:38 UTC, Nil-Cipher commented
@VIKTORVAV99 should be good now.

2023-07-08 14:40 UTC, VIKTORVAV99 commented
I'll try and take a look later today. 👍🏼

2023-07-29 22:44 UTC, Nil-Cipher commented
@VIKTORVAV99 updates?

2023-08-05 11:50 UTC, VIKTORVAV99 commented
Ah sorry @Nil-Cipher this slipped under my radar when doing all the dependabot dependency updates.
I'll take a look at it later today.

2023-08-06 16:43 UTC, VIKTORVAV99 commented on config/zones/CA-ON.yaml
> +      source: "Mallia, E., and G. Lewis. “Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada.” The International Journal of Life Cycle Assessment, vol. 1
```suggestion
      source: Mallia, E., and G. Lewis. "Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada." The International Journal of Life Cycle Assessment, vol. 18, no. 2, 2012, pp. 377–391
```

2023-08-06 16:43 UTC, VIKTORVAV99 commented on config/zones/CA-ON.yaml
> +      source: "Mallia, E., and G. Lewis. “Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada.” The International Journal of Life Cycle Assessment, vol. 1
```suggestion
      source: Mallia, E., and G. Lewis. "Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada." The International Journal of Life Cycle Assessment, vol. 18, no. 2, 2012, pp. 377–391
```

2023-08-06 16:43 UTC, VIKTORVAV99 commented on config/zones/CA-ON.yaml
> +      source: "Mallia, E., and G. Lewis. “Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada.” The International Journal of Life Cycle Assessment, vol. 1
```suggestion
      source: Mallia, E., and G. Lewis. "Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada." The International Journal of Life Cycle Assessment, vol. 18, no. 2, 2012, pp. 377–391
```

2023-08-06 16:43 UTC, VIKTORVAV99 commented on config/zones/CA-ON.yaml
> +      source: "Mallia, E., and G. Lewis. “Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada.” The International Journal of Life Cycle Assessment, vol. 1
```suggestion
      source: Mallia, E., and G. Lewis. "Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada." The International Journal of Life Cycle Assessment, vol. 18, no. 2, 2012, pp. 377–391
```

2023-08-06 16:43 UTC, VIKTORVAV99 commented on config/zones/CA-ON.yaml
> +  ? "Mallia, E., and G. Lewis. “Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada.” The International Journal of Life Cycle Assessment, vol. 18, no. 2,
```suggestion
  Mallia, E., and G. Lewis. "Life Cycle Greenhouse Gas Emissions of Electricity Generation in the Province of Ontario, Canada." The International Journal of Life Cycle Assessment, vol. 18, no. 2, 2012, pp. 377–391:
    link: https://doi.org/10.1007/s11367-012-0501-0
```
Don't forget to remove the duplicate link under this line.

2023-08-10 01:43 UTC, Nil-Cipher commented
@VIKTORVAV99 Should be good now!

2023-08-11 21:24 UTC, VIKTORVAV99 reviewed
Why did you add back the weird double quotes and wrap it in single quotes again? This should not be needed for YAML.

(the doi link is also back in the values for the emission factors).

2023-08-13 01:22 UTC, Nil-Cipher commented
> Why did you add back the weird double quotes and wrap it in single quotes again? This should not be needed for YAML.
> 
> (the doi link is also back in the values for the emission factors).

Hm, maybe I merged things in the wrong order, sorry about this.

2023-08-13 01:30 UTC, Nil-Cipher commented
Okay, this should not have been this painful, but I think it is good.

2023-10-13 14:11 UTC, VIKTORVAV99 commented
Seems like I missed the last change in here and I'm sorry about that.

But this has been resolved in another PR now so closing this one.

(A tip for the future is to re-request a review after changes, it's hard to keep up with all the "normal" notifications from GitHub and review requests end up automatically in my tools so they are easier to keep track of.)

2024-09-19 21:09 UTC, madsnedergaard commented
Seems like we forgot to actually close this after https://github.com/electricitymaps/electricitymaps-contrib/pull/5987 - thanks again for the work put into this, your work was carried over in the new PR and the final small things fixed :)

2024-09-19 21:09 UTC, closed without merging