Fix cy capacity parser
electricitymaps/electricitymaps-contrib pull request #5746
Opened 2023-08-16 18:24 UTC by silimotion

## Issue

Closes #5743 

## Description

This solves the issue by updating the name of the html table that should be parsed
I also added some error handling to only run the code when using the realtime source

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [X] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-08-17 12:15 UTC, VIKTORVAV99 requested changes
Does this work locally for you?
Capacity seems to be an empty object no matter if it's run with a target datetime or not.

2023-08-17 12:24 UTC, VIKTORVAV99 commented
🤔 It should not be doing that.

2023-08-17 12:28 UTC, VIKTORVAV99 commented
The test parser returns None as expected.
So it's something in the parser itself that is changing it. I suspect it is how it's set up with the class based structure.
If I log the target_datetime before any of the class stuff I get this:
```
❯ poetry run test_parser CY
Target datetime: None
```

2023-08-17 12:59 UTC, silimotion commented
Oh, I see it now. It seems it sets the current time if there is no date in line 122. I can edit it later. As there is always a target_datetime some code was never run.

2023-08-17 15:06 UTC, silimotion commented
It should work now. I missed the line where the target_datetime was set because I though I was editing the entrypoint because both functions have the same "fetch_production" name. Can we rename the function inside the Class CyprusParser to something like parse_production? This would stop the name collision. Or just altogether refactor the module to remove the CypusParser class? I just don't see the point in it.

2023-08-21 19:48 UTC, VIKTORVAV99 requested changes

2023-08-21 19:48 UTC, VIKTORVAV99 commented on parsers/CY.py
>          return parser.fetch_production(target_datetime)
This won't work. The isinstance method can not be used with a optional type (at least not in python 3.8). But I don't think you need it at all with the other changes you have made.
```suggestion
    return parser.fetch_production(target_datetime)
```

2023-08-24 19:37 UTC, VIKTORVAV99 approved these changes
Thanks for updating the parser!

2023-08-24 19:39 UTC, merged