Remove oahu parser
electricitymaps/electricitymaps-contrib pull request #5747
Opened 2023-08-17 02:39 UTC by nickwohnhas

## Issue
The data source for Oahu no longer displays any information: https://www.islandpulse.org/.  

Closes #5660

## Description
Per the discussion [here](https://github.com/electricitymaps/electricitymaps-contrib/issues/5660) it may be preferable to remove the data parser altogether because the map is currently showing incorrect data for Oahu, HI.  I made an attempt to remove the relevant code, but I'm very new to this project so if I missed something or this isn't needed please let me know!  I did see that the mockserver has some JSON data for Oahu and I can remove that if necessary.  

### Preview

<img width="1270" alt="Screen Shot 2023-08-16 at 10 06 55 PM" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/38133769/10bd8099-74d3-4b1b-b243-04fc9a42bf03">

### Double check

- [x] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [x] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-08-17 10:02 UTC, VIKTORVAV99 requested changes
Thanks for opening a PR!
There are a few things that will have to change in here as it's currently removing a bit too much.

It also won't close the issue as Oahu is also estimated. But I'll open a PR for that in the backend.

2023-08-17 10:02 UTC, VIKTORVAV99 commented on parsers/US_HI.py
It would be better to move this to `parsers/archived` instead of fully removing it.

2023-08-20 20:14 UTC, nickwohnhas commented on parsers/US_HI.py
Hey @VIKTORVAV99 , thanks so much for the review! I went ahead and restored all of the deleted files, and moved the `US_HI.py` parser into `parsers/archived`.

2023-08-21 20:00 UTC, VIKTORVAV99 commented on parsers/US_HI.py
Thanks, but in you restored a tiny bit too much. We still need to remove the parsers object from the config file otherwise the backend will try and call the parser.

2023-08-24 19:35 UTC, VIKTORVAV99 commented
Just to provide an update, the backend PR is still open but I expect we can merge that soon. As soon that is merged I will merge this.

2023-08-25 16:45 UTC, nickwohnhas commented
> Just to provide an update, the backend PR is still open but I expect we can merge that soon. As soon that is merged I will merge this. (Assuming the parser objects have been removed from the zone config).

Awesome!  I'm working on removing the parser from the zone config now.  Sorry for the delay

2023-08-25 17:14 UTC, nickwohnhas commented on parsers/US_HI.py
I've removed the parser object from the config file.  If I've misunderstood please let me know, but I think that was the last outstanding item on this PR.

2023-08-28 14:25 UTC, VIKTORVAV99 approved these changes
LGTM! 🎉

2023-08-28 14:25 UTC, merged