updated parser to handle battery storage
electricitymaps/electricitymaps-contrib pull request #5835
Opened 2023-09-06 14:09 UTC by mathilde-daugy

## Issue

Power plant mapping was updated with battery storage facilities but the current parser was not built to capture that

## Description

update the parser to collect battery storage
remove the pivot table part because it is not very efficient method

### Preview

<img width="802" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/107848894/863b5393-f5fa-4d15-8710-639e32e5ae46">

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-09-06 14:30 UTC, VIKTORVAV99 reviewed
The battery storage values seems to only be positive (storage) but no negative values (discharge). Is storage and discharge reported on units or is there something we are missing in here?

Also one suggestion, but things seems to be working as expected so feel free to ignore.

2023-09-06 14:30 UTC, VIKTORVAV99 commented on parsers/PH.py
> +            if row["production_mix"] == "production":
Wouldn't `if row["mode"] in PRODUCTION_MODES` be easier and we could skip the whole "production_mix" column? (same for storage but with a storage list)

2023-09-07 07:13 UTC, pierresegonne requested changes

2023-09-07 07:13 UTC, pierresegonne commented on parsers/PH.py
> +    df["production_mix"] = None
I don't think the name of the column is self-descriptive.

If I understand correctly, we end up with:

```
idx, mode, value, production_mix 
dt, coal, 1239, "production"
```

If that's the case, then I would second Viktor's comment: do we even need that, and can't we directly use the mode column for that info?

2023-09-07 07:14 UTC, pierresegonne commented
> The battery storage values seems to only be positive (storage) but no negative values (discharge). Is storage and discharge reported on units or is there something we are missing in here?

I think it's because we filter items with positive contributions to the grid. We could make an exception for resources that are matched to a storage system

2023-09-07 08:24 UTC, VIKTORVAV99 commented
> > The battery storage values seems to only be positive (storage) but no negative values (discharge). Is storage and discharge reported on units or is there something we are missing in here?
> 
> I think it's because we filter items with positive contributions to the grid. We could make an exception for resources that are matched to a storage system

Yeah I think we have to do that, otherwise we would loose data that we might not be able to refetch on a later date which might influence the carbon intensity if we re-work how storage emission factors are attributed (say only during charging/storage instead of a yearly average as an example).

2023-09-07 08:40 UTC, VIKTORVAV99 commented on parsers/PH.py
> +                storage_mix.add_value(mode, row["production"])
```suggestion
                storage_mix.add_value(mode, -row["production"])
```
This gets us every time...
can we add something in the long term planning to fix this?

2023-09-08 09:31 UTC, VIKTORVAV99 commented
> > The battery storage values seems to only be positive (storage) but no negative values (discharge). Is storage and discharge reported on units or is there something we are missing in here?
> 
> I think it's because we filter items with positive contributions to the grid. We could make an exception for resources that are matched to a storage system

Do we even need filter this? The new parser classes would correct these to 0 when adding them to production, or would that include a lot more items that are consumption only?

2023-09-11 06:49 UTC, pierresegonne commented
> Do we even need filter this? The new parser classes would correct these to 0 when adding them to production, or would that include a lot more items that are consumption only?

I would rather not rely on an downstream process to correct these values when we know that they don't even represent generation units. The data contains data both for consumer nodes and generators :)

2023-09-14 07:35 UTC, closed without merging