Jl/nova scotia update hydro capacity
electricitymaps/electricitymaps-contrib pull request #6194
Opened 2023-11-30 10:00 UTC by lav-julien

## Description

Update hydro capacity and oil/natural gas of CA-NS parser. Source: https://www.nspower.ca/docs/default-source/monthly-reports/10-year-system-outlook-report.pdf?sfvrsn=d39bca29_62

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [X] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-12-04 13:36 UTC, pierresegonne requested changes
Could you update the CA-NS.yaml with the new hydro capacity please?

2023-12-11 16:47 UTC, lav-julien commented on parsers/CA_NS.py
> +            "oil": mix["CT's"] / 100.0,
as mentioned in the report here: https://www.nspower.ca/docs/default-source/monthly-reports/10-year-system-outlook-report.pdf?sfvrsn=d39bca29_62, the data reported under CT's (combustion turbines) is oil generation and not natural gas generation

2023-12-12 16:19 UTC, VIKTORVAV99 approved these changes
From my side this looks good but I do think we need to be careful with the CT data as they mention this (might) include hydrogen in the future.

2023-12-13 14:36 UTC, pierresegonne approved these changes

2023-12-13 14:47 UTC, merged