NZ parser: Update oil for name change
electricitymaps/electricitymaps-contrib pull request #6269
Opened 2023-12-20 21:32 UTC by drc38

## Issue

## Description
Updates the parser to match the latest descriptions from Transpower for the Oil category

### Preview

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"`
- [ ] I have run `pnpx prettier --write .` and `poetry run format` to format my changes.

2023-12-22 16:18 UTC, VIKTORVAV99 requested changes
One tiny change needed then this will look good, thanks for doig this.

2023-12-22 16:18 UTC, VIKTORVAV99 commented on parsers/NZ.py
> +            "oil": productions.get("Diesel\/Oil", {"generation": None})["generation"],
```suggestion
            "oil": productions.get("Diesel/Oil", {"generation": None})["generation"],
```

2023-12-22 16:18 UTC, VIKTORVAV99 commented on parsers/NZ.py
> +            "oil": productions.get("Diesel\/Oil", {"capacity": None})["capacity"],
```suggestion
            "oil": productions.get("Diesel/Oil", {"capacity": None})["capacity"],
```

2023-12-29 07:25 UTC, drc38 commented on parsers/NZ.py
> +            "oil": productions.get("Diesel\/Oil", {"generation": None})["generation"],
Thanks, now fixed

2023-12-29 10:07 UTC, VIKTORVAV99 approved these changes
Thanks for updating this parser!

2023-12-29 10:07 UTC, merged