refactor(EIA): remove usage of 'arrow' dependency
electricitymaps/electricitymaps-contrib pull request #7488
Opened 2024-11-30 20:13 UTC by jayaddison

## Issue

Contributes-to resolving issue #6135.

## Description

Refactor-out usage of the `arrow` datetime parsing library from the `EIA` parser.

### Preview

```
[{'datetime': datetime.datetime(2022, 2, 27, 23, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -11.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 2.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 1, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 2.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 2, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 3.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 3, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -3.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 4, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -6.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 5, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -4.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 6, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -11.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 7, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -7.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 8, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -15.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 9, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -10.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 10, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -12.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 11, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -4.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 12, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -7.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 13, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': -7.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 14, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 5.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 15, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 13.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 16, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 8.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 17, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 12.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 18, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 6.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 19, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 6.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 20, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 10.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 21, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 17.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 22, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 12.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>},
 {'datetime': datetime.datetime(2022, 2, 28, 23, 0, tzinfo=tzfile('/usr/share/zoneinfo/UTC')),
  'netFlow': 11.0,
  'sortedZoneKeys': 'CA-SK->US-CENT-SWPP',
  'source': 'eia.gov',
  'sourceType': <EventSourceType.measured: 'measured'>}]
```

### Double check

- [x] I have tested my parser changes locally with ~~`poetry run test_parser "US-CAL-LDWP"`~~ `` (I encountered infinite-recursion during `ssl` module monkey-patching when attempting the `test_parser` approach)
- [ ] ~~I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.~~ (N/A - does not affect frontend/JS code)

2024-12-12 08:47 UTC, VIKTORVAV99 requested changes
There seems to be some differences in how the datetime is converted that needs to be fixed.

But thanks for the PR, it's a very good start!

2024-12-12 12:26 UTC, jayaddison commented on parsers/EIA.py
> +    return _conform_timestamp_convention(dt.replace(tzinfo=tz.gettz("UTC")))
Thank you; I'll apply those changes and re-test within the next few days (I think I may need to request another API key).

I did think about the `.to` timezone-conversion logic during development, but IIRC determined that the relevant object is a naive datetime, and took that to mean that no actual conversion was being applied -- but I should go back to confirm whether that's definitely true, and even if it is, it's not a great (or transparent) reason to remove that part of the logic.

2024-12-12 12:27 UTC, jayaddison commented on parsers/EIA.py
> +    return _conform_timestamp_convention(dt.replace(tzinfo=tz.gettz("UTC")))
(NB: perhaps I can also add some supporting unit test coverage alongside those changes)

2024-12-15 23:26 UTC, jayaddison commented on parsers/EIA.py
> +    return _conform_timestamp_convention(dt.replace(tzinfo=tz.gettz("UTC")))
The explanation of what's going on here is that the EIA API allows data to be reported hourly either in native UTC or using local-time intervals.

We're already using the former UTC intervals (`frequency=hourly`) - so the data in the response shouldn' require any timezone translation (the existing use of `.to(...)` was redundant, as would be `.astimezone(timezone.utc)`).

I'm not sure I've done a great job of documenting that with the comments / suggested code structure; I'd be glad for any ideas about how to make this more readable.

2024-12-27 19:23 UTC, VIKTORVAV99 approved these changes
LGTM! 🎉

Thanks for adding the extra tests as well!

2024-12-27 19:24 UTC, merged

2024-12-28 00:03 UTC, jayaddison commented
Thank you @VIKTORVAV99!  Glad to help continue the cleanup.