Pumping storage fix for CZ parser
electricitymaps/electricitymaps-contrib pull request #7530
Opened 2024-12-07 23:39 UTC by dermotmolony

## Issue

Closes #5426

## Description

Creates get_pumping_load function which fetches pumping load data from ceps.cz and computes the current load at each timestamp that is being used for pumping. 

Modifies fetch_production to call get_pumping_load, whose dictionary is then used to add the amount of energy being stored to hydro at each timestamp.

### Preview

The hydro storage values from fetch_production() showing the new positive values calculated from load_including_pumping-load
<img width="356" alt="image" src="https://github.com/user-attachments/assets/d56f522f-13f4-4d81-8ff5-70496202f90a">

### Double check

- [ ] I have tested my parser changes locally with `poetry run test_parser "zone_key"` - I got the error marking ":( >2h from now !!!" but the original CZ parser code produces the exact same error locally. I tried to same if it was a time conversion issue but didn't have any luck locating the source of the issue
- [X] I have run `pnpx prettier@2 --write .` and `poetry run format` in the top level directory to format my changes.

2024-12-11 09:42 UTC, VIKTORVAV99 requested changes
There are some type issues to look at and how to better use the parser functions as intended but otherwise it seems to work.

Thanks for opening the PR.

2024-12-11 09:42 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +) -> list:
This has the return type list.

2024-12-11 09:42 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +    return pumping_load_at_time_dict
But this is returning a dict.

2024-12-11 09:42 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +            )
This also contains type errors. Such as `"__getitem__" method not defined on type "PageElement"`

2024-12-11 09:42 UTC, VIKTORVAV99 commented on parsers/CZ.py
> +                        pumping_storage += pumping_load_at_time[values["date"]]
Why are you summing things up here?

If there are multiple storage entries they should be looped over and add_value should be called on each of them as it handles summing up values of the same type.

2025-03-10 23:11 UTC, madsnedergaard commented
Closing due to inactivity, feel free to reopen if you decide to pick this up again :)

2025-03-10 23:11 UTC, closed without merging